// ✅ Master list — all quizzes (includes both Live & Async)
export const allQuizzes = [
  {
    id: "qz101",
    title: "Advanced JavaScript Concepts",
    category: "Programming",
    totalQuestions: 20,
    duration: "30 mins",
    mode: "live",
    difficulty: "Hard",
    participants: 45,
    dateTime: "Oct 23, 02:00 PM",
    createdBy: "John Doe",
  },
  {
    id: "qz102",
    title: "React Hooks Deep Dive",
    category: "Programming",
    totalQuestions: 25,
    duration: "45 mins",
    mode: "async",
    difficulty: "Medium",
    participants: 123,
    dueDate: "Oct 30, 11:59 PM",
    createdBy: "Sarah Smith",
  },
  {
    id: "qz103",
    title: "Data Structures & Algorithms",
    category: "Programming",
    totalQuestions: 30,
    duration: "50 mins",
    mode: "live",
    difficulty: "Hard",
    participants: 87,
    dateTime: "Nov 02, 04:30 PM",
    createdBy: "John Doe",
  },
  {
    id: "qz104",
    title: "Python for Beginners",
    category: "Programming",
    totalQuestions: 15,
    duration: "25 mins",
    mode: "async",
    difficulty: "Easy",
    participants: 210,
    dueDate: "Nov 05, 08:00 PM",
    createdBy: "Emily Carter",
  },
  {
    id: "qz105",
    title: "Frontend Development Challenge",
    category: "Web Development",
    totalQuestions: 28,
    duration: "40 mins",
    mode: "live",
    difficulty: "Medium",
    participants: 152,
    dateTime: "Nov 08, 06:00 PM",
    createdBy: "David Kim",
  },
  {
    id: "qz106",
    title: "Database Design Fundamentals",
    category: "Databases",
    totalQuestions: 22,
    duration: "35 mins",
    mode: "async",
    difficulty: "Medium",
    participants: 97,
    dueDate: "Nov 10, 10:00 PM",
    createdBy: "AI Generator",
  },
];
